config/routes.rb
Rails.application.routes.draw do
  get 'user', to: 'user#index'
  resources :admin, only: [:index, :show]
  devise_for :users 
 

  root "home#index"

  resources :questions do 
    resources :options
  end

  resources :test_questions do
    resources :question_bodies
  end
  get '/test_questions/:id/start_test', to: 'test_questions#start_test', as: 'start_test'



  # resources :languages do
  #   post 'create_ajax', on: :collection
  # end

  resources :question_bodies do
    resources :options 
  end

  resources :results do
    post 'submit_option', on: :collection
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :questions
  has_many :test_questions
  has_many :topics, through: :test_questions
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :optionable, polymorphic: true
  validates :text, presence: true
  has_many :results
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :options, as: :optionable

  belongs_to :language, dependent: :destroy
  belongs_to :topic, dependent: :destroy
  
  enum difficulty: [:easy, :medium, :hard]
  enum question_type: [:Single_choice_question , :multi_choice_question]

end

app/models/question_body.rb
class QuestionBody < ApplicationRecord
  belongs_to :test_question
  has_many :options, as: :optionable
  has_many :results
  # self.per_page = 1
  validates :text, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :option
  belongs_to :question_body
end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  has_one_attached :image
  belongs_to :language, dependent: :destroy
  belongs_to :topic, dependent: :destroy
  has_many :question_bodies
  # accepts_nested_attributes_for :question_bodies, allow_destroy: true, reject_if: :all_blank

  validates :description, presence: true

  enum difficulty: [:easy, :medium, :hard]
  enum question_type: [:Single_choice_question , :multi_choice_question]

  
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :test_questions
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :results


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attribute :name, :string
  
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users = User.all
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
  end

  def index
    @questions = Question.all
    @q=Question.find(params[:question_id])
    @answers=@q.answers
  end

  def create
    question = Question.find(params[:question_id])
    @answer = question.answers.create(answer_params)
    if @answer.save
      redirect_to questions_path
    else
      render 'new'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:ans,:correct)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    if user_signed_in?
      if current_user.role.eql? "admin"
        redirect_to admin_index_path
      else
        redirect_to user_path
      end
    end
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @language = Language.all

  end




  def create_ajax
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.json { render json: @language, status: :created }
      else
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

 

  private

  def language_params
    params.require(:language).permit(:name)
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def new
    @optionable = find_optionable
  end

  def index
    @questions = Question.all
    if params[:question_id]
      @q=Question.find(params[:question_id])
      @options=@q.options
    end
  end

  def create
    @optionable = find_optionable
    @option = @optionable.options.create(answer_params)
    # debugger
    if @option.save
      redirect_to test_questions_path
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:option).permit(:text,:correct)
  end

  def find_optionable
    if params[:question_body_id]
      QuestionBody.find(params[:question_body_id])
    elsif params[:question_id]
      Question.find(params[:question_id])
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = Question.all
    
    @options=Option.all
  end

  def new
    @question = Question.new
    
  end

  def create 
    @question = Question.create(question_params)
    
    if @question.save 
         
        flash[:success] = "You have successfully created question"
        redirect_to questions_path
    else
        render 'new'
    end
  end 

  def edit
    @question = Question.find(params[:id])
 end
  
 def update
  @question = Question.find(params[:id])
     if @question.update(question_params)
      
         flash[:success] = "You have successfully updated your questions"
         redirect_to questions_path(@question)
     else
         render 'new'
     end
 end

 def destroy
  
  @question = Question.find(params[:id])
  @question.destroy
  redirect_to questions_path(@question)
 end

  private

  def question_params
    params.require(:question).permit(:text,:question_type,:difficulty,:language_id,:topic_id)
  end


end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def submit_option
    # @test_question = TestQuestion.find(params[:id])
    @question_body = QuestionBody.find(params[:question_body_id])
    if params[:option_id]
      @option = Option.find(params[:option_id])
      @result = Result.create(question_body: @question_body, option: @option, user: current_user)
      # debugger
      if @result.save
        
        redirect_back(fallback_location: root_path)
      else
        
      end
    end
    @result = Result.create(question_body_id: @question_body)
  
    if @result.save
      
      redirect_back(fallback_location: root_path)
    else
      
    end
  end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController

  def index
    @topic = Topic.all
    
   
  end

  def new
    @topic = Topic.new
    
  end

  def create 
      @topic = Topic.create(question_params)
    
    if @topic.save 
         
        flash[:success] = "You have successfully created question"
        redirect_to new_question_path
    else
        render 'new'
    end
  end 

  private

  def question_params
    params.require(:topic).permit(:name)
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h1 style="text-align:center;color:white;background-color:red">Welcome To our Website</h1>

<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner mt-2 border border-dark ">
    <div class="carousel-item active">
      <img src="https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600" class="d-block  w-100" height='600vh' alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://www.shutterstock.com/image-photo/online-training-young-guy-learns-260nw-1716024532.jpg" class="d-block  w-100" height='600vh' alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnBqJCWbSKGUxnTXOz6f-vi6pFCDjM8twMkt4dWb9c&s" class="d-block  w-100" height='600vh' alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container">
 <h1 style="text-align:center;color:white; margin-top:10px;background-color:red">Some Information</h1>


  <div class="container mt-3">
  <div class="card mb-3" style="max-width: 1200px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="https://thumbs.dreamstime.com/b/education-learning…llustration-art-isolated-background-111644290.jpg" class="img-fluid rounded-start" style="box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h3 class="card-title">INFORMATION</h3><hr>
          <p class="card-text">* Everyone can use this website.</p>
          <p class="card-text">* The purpose for this website is to give knowledge for their carrier with their performance.</p>
          <p class="card-text">* Our team serves the nation to educate the students and get ready for their future.</p>
          <p class="card-text">* If you want to increase your technical knowledge then you should use this website.</p>
          
          <p class="card-text"><small class="text-muted">Last updated few months ago</small></p>
        </div>
      </div>
    </div>
  </div>
  </div>
  <h6>Here, you can learn technical knowledge very easily and boost your performance. </h6>
  <p>You will be able to learn following technology. </p>
 
  <ul>
    <li>C</li>
    <li>C++</li>
    <li>Java</li>
    <li>Python</li>
    <li>ROR</li>
    <li>React Js</li>
  </ul>
  <p>In every step you have some questions which may be MCQ, SATQ, LATQ and you have to give their answer. </p>
  <p>After clearing every step you can get respective certificate and your level will grow up. </p>
  
</div>

app/views/options/index.html.erb
<h1 style="text-align:center">ALL Question and Answer</h1><hr>
<div class="container">
<% @questions.each do |question| %>


  <div class="card m-2 " style="width: 80rem;">

  <% if current_user.role.eql? "admin" %>
  <div class="container d-flex">
    <%= link_to "Add Answer", new_question_option_path(question), class: "btn btn-primary mt-2"%>
  </div>
  <%end%>

  
  
    <div class="card-body ">
    <div class="container d-flex justify-content-between pe-2 ">
       <h5 class="card-title"><b>Question :-  <%= question.id %>. </b><%= question.text %></h5>
       <p>Language:-<%= question.language&.name %><br>Topic:-<%= question.topic&.name %><br>Type:-<%= question.question_type %></p> 
    </div>
      
       <% question.options.each do |option| %>
          <ul>
            <li><%=  radio_button 'option', 'ans', option.text %> <%=option.text%>

           
          
             <% if option.correct ==  true %>
                <%# radio button with value "my_value" has been selected %>
                 <h6 style="color:green">Correct Answer</h6>
             <% else %>
                <%# # radio button with value "my_value" has not been selected %>
                 <h6 style="color:red">Wrong Answer</h6>
              <%end%></li>
          </ul> 
       <%end%>
       <%= link_to "Hide options", questions_path(question), class: "btn btn-warning" %>
      
    </div>
  </div>

<% end %>
</div>

app/views/options/new.html.erb
<%= form_with model: [ @optionable, @optionable.options.build ] do |f| %>

  <div class="container-sm">  
    <div class="row mb-3 mt-5">
      <strong><%= f.label :enter_answer %></strong>
      <%= f.text_field :text, placeholder: "Enter Question" %>
    </div>

      <strong>Correct Answer</strong>
      <div class="column mb-3">
        <%= f.label :true %>
        <%= f.radio_button :correct, 'true' %>    
      </div>
            
      <div class="column mb-3">
        <%= f.label :false %>
        <%= f.radio_button :correct,  'false'%>    
      </div>

    <%= f.submit "submit", class:"btn btn-success mt-3" %>
  </div>

<%end %>

app/views/questions/edit.html.erb
<h1 style="text-align:center;color:white;background-color:red">Edit Question Detail</h1>

<%= form_with model: @question do |f| %>
  <div class="container-sm">
  
    <div class="container d-flex me-5">

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_language_of_question %></strong>
        <%= f.select :language_id, Language.pluck(:name, :id), {}, {data: {controller: 'slim'}}  %>
      </div>

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_topic_of_question %></strong>
        <%= f.select :topic_id, Topic.pluck(:name, :id)  %>

      </div>

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_difficulty_level %></strong>
        <%= f.select :difficulty, TestQuestion.difficulties.keys.to_a %>

      </div>

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_question_type %></strong>
        <%= f.select :question_type, TestQuestion.question_types.keys.to_a %>

      </div>

    </div>

    <div class="row mb-3 mt-5">
      <strong><%= f.label :enter_question %></strong>
      <%= f.text_field :text, placeholder: "Enter Question", autofocus: true %>
    </div>

    <%# <div class="class">
      <%= link_to "Add Answer", new_question_answer_path %>
    <%# </div> %> 

    <%= f.submit "submit", class:"btn btn-success mt-3" %>
  </div>

<%end%>

app/views/questions/index.html.erb
<h1 style="text-align:center">ALL Question and Answer</h1><hr>
<div class="container">
<% @questions.each do |question| %>


  <div class="card m-2 " style="width: 80rem;">
  <% if current_user.role.eql? "admin" %>
    <div class="container d-flex mt-2">
      <%= link_to "Add Answer", new_question_option_path(question),class: "btn btn-primary " %>
      <%= link_to "Edit Question", edit_question_path(question),class: "btn btn-warning ms-2" %>
      <%= link_to "Delete Question", question_path(question), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } ,class: "btn btn-danger ms-2" %>
    </div>
  <%end%>
  
  
    <div class="card-body ">
    <div class="container d-flex justify-content-between pe-2 ">
       <h5 class="card-title"><b>Question :-  <%= question.id %>. </b><%= question.text %></h5>
       <p>Language:-<%= question.language&.name %><br>Topic:-<%= question.topic&.name %><br>Type:-<%= question.question_type %></p>  
    </div>
    <%= link_to "see options", question_options_path(question), class: "btn btn-success" %>
     

    </div>
  </div>

<% end %>
</div>

app/views/questions/new.html.erb
<h1 style="text-align:center;color:white;background-color:red">Enter Question Detail</h1>

<%= form_with model: @question do |f| %>
  <div class="container-sm">
  
    <div class="container d-flex me-5">

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_language_of_question %></strong>
        <%= f.select :language_id, Language.pluck(:name, :id), {}, {data: {controller: 'slim'}}  %>
      </div>

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_topic_of_question %></strong>
        <%= f.select :topic_id, Topic.pluck(:name, :id)  %>

      </div>

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_difficulty_level %></strong>
        <%= f.select :difficulty, TestQuestion.difficulties.keys.to_a %>

      </div>

      <div class="column mb-3 mt-2">
        <strong><%= f.label :select_question_type %></strong>
        <%= f.select :question_type, TestQuestion.question_types.keys.to_a %>

      </div>

    </div>

    <div class="row mb-3 mt-5">
      <strong><%= f.label :enter_question %></strong>
      <%= f.text_field :text, placeholder: "Enter Question", autofocus: true %>
    </div>

    <%# <div class="class">
      <%= link_to "Add Answer", new_question_answer_path %>
    <%# </div> %> 

    <%= f.submit "submit", class:"btn btn-success mt-3" %>
  </div>

<%end%>