config/routes.rb
Rails.application.routes.draw do
  get 'user', to: 'user#index'
  resources :admin, only: [:index, :show]
  devise_for :users 
 

  root "home#index"

  resources :questions do 
    resources :options
  end

  resources :test_questions do
    resources :question_bodies
  end
  get '/test_questions/:id/start_test', to: 'test_questions#start_test', as: 'start_test'



  # resources :languages do
  #   post 'create_ajax', on: :collection
  # end

  resources :question_bodies do
    resources :options 
  end

  resources :results do
    post 'submit_option', on: :collection
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :questions
  has_many :test_questions
  has_many :topics, through: :test_questions
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :optionable, polymorphic: true
  validates :text, presence: true
  has_many :results
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :options, as: :optionable

  belongs_to :language, dependent: :destroy
  belongs_to :topic, dependent: :destroy
  
  enum difficulty: [:easy, :medium, :hard]
  enum question_type: [:Single_choice_question , :multi_choice_question]

end

app/models/question_body.rb
class QuestionBody < ApplicationRecord
  belongs_to :test_question
  has_many :options, as: :optionable
  has_many :results
  # self.per_page = 1
  validates :text, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :option
  belongs_to :question_body
end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  has_one_attached :image
  belongs_to :language, dependent: :destroy
  belongs_to :topic, dependent: :destroy
  has_many :question_bodies
  # accepts_nested_attributes_for :question_bodies, allow_destroy: true, reject_if: :all_blank

  validates :description, presence: true

  enum difficulty: [:easy, :medium, :hard]
  enum question_type: [:Single_choice_question , :multi_choice_question]

  
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :test_questions
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :results


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attribute :name, :string
  
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users = User.all
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
  end

  def index
    @questions = Question.all
    @q=Question.find(params[:question_id])
    @answers=@q.answers
  end

  def create
    question = Question.find(params[:question_id])
    @answer = question.answers.create(answer_params)
    if @answer.save
      redirect_to questions_path
    else
      render 'new'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:ans,:correct)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    if user_signed_in?
      if current_user.role.eql? "admin"
        redirect_to admin_index_path
      else
        redirect_to user_path
      end
    end
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @language = Language.all

  end




  def create_ajax
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.json { render json: @language, status: :created }
      else
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

 

  private

  def language_params
    params.require(:language).permit(:name)
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def new
    @optionable = find_optionable
  end

  def index
    @questions = Question.all
    if params[:question_id]
      @q=Question.find(params[:question_id])
      @options=@q.options
    end
  end

  def create
    @optionable = find_optionable
    @option = @optionable.options.create(answer_params)
    # debugger
    if @option.save
      redirect_to test_questions_path
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:option).permit(:text,:correct)
  end

  def find_optionable
    if params[:question_body_id]
      QuestionBody.find(params[:question_body_id])
    elsif params[:question_id]
      Question.find(params[:question_id])
    end
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def submit_option
    # @test_question = TestQuestion.find(params[:id])
    @question_body = QuestionBody.find(params[:question_body_id])
    if params[:option_id]
      @option = Option.find(params[:option_id])
      @result = Result.create(question_body: @question_body, option: @option, user: current_user)
      # debugger
      if @result.save
        
        redirect_back(fallback_location: root_path)
      else
        
      end
    end
    @result = Result.create(question_body_id: @question_body)
  
    if @result.save
      
      redirect_back(fallback_location: root_path)
    else
      
    end
  end
end

app/controllers/test_questions_controller.rb
class TestQuestionsController < ApplicationController
  before_action :authenticate_user!
  require "will_paginate-bootstrap"

  def index
    @test_questions = TestQuestion.all
    
    
  end

  def new
      @test_question = TestQuestion.new
      
  end

  def show
    @test_question = TestQuestion.find(params[:id])
    # @test_question = TestQuestion.find(params[:test_question_id])
  end

  def create 
      
      @test_question = TestQuestion.create(question_params)
    
    if @test_question.save 
          
        flash[:success] = "You have successfully created question"
        redirect_to test_questions_path
    else
        render 'new'
    end
  end 
  
  def edit
    @test_question = TestQuestion.find(params[:id])
 end
  
 def update
  @test_question = TestQuestion.find(params[:id])
     if @test_question.update(question_params)
      
         flash[:success] = "You have successfully updated your information"
         redirect_to test_questions_path(@test_question)
     else
         render 'new'
     end
 end

 def destroy
  
  @test_question = TestQuestion.find(params[:id])
  @test_question.destroy
  redirect_to test_questions_path(@test_question)
 end

 def start_test
  @test_question = TestQuestion.find(params[:id])
  @body = @test_question.question_bodies
  @all_question = TestQuestion.find(params[:id]).question_bodies.paginate(page: params[:page], per_page: 1)
  #@all_question = test_question.question_bodies
 # @all_question = test_question.question_bodies.paginate(page: params[:page])
  @question_body = QuestionBody.find(params[:id])
  @opt=@question_body.options
  
 end

 
    

    private
  
    def question_params
      params.require(:test_question).permit(:text,:image,:passing_marks,:no_of_question,:full_marks,:description,:question_type,:difficulty,:topic_id,
                                          :language_id, question_bodies_attributes: [:id, :text, :_destroy])
                              
    end
  
  
  end

app/controllers/topic_controller.rb
class TopicController < ApplicationController

  def index
    @topic = Topic.all
    
   
  end

  def new
    @topic = Topic.new
    
  end

  def create 
      @topic = Topic.create(question_params)
    
    if @topic.save 
         
        flash[:success] = "You have successfully created question"
        redirect_to new_question_path
    else
        render 'new'
    end
  end 

  private

  def question_params
    params.require(:topic).permit(:name)
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/test_questions/_question_body_fields.html.erb
<!-- Nested Form for f -->
<%# <div class="question_body-fields">
  <Strong><%= form.label :question_text, class: "mt-3" %></strong>
  <%# <%= form.text_field :text, placeholder: "Enter Question", class: "mb-3 form-control" %>

  <%# <%= link_to_remove_nested(form) do %>
    <%# <span>
      <span>Remove</span>
    </span>
  <%end%>

<%# </div> %> 

<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :question_text %>
  <%= f.text_field :text %>

  <button type="button" data-action="nested-form#remove">Remove Question</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/test_questions/_rules.html.erb
<h4 style="color:blue">Rules for test</h4><hr>
<p>* You will have to complete the test in the given time.</p>
<p>* Complete this test in single attempt.</p>
<p>* You have <%= @test_question.no_of_question %> questions.</p>
<p>* You have <%= @test_question.no_of_question %> minutes to complete this test.</p>
<p>* Each Question will carry 1 marks.</p>
<p>* There is no negative marking for the questions.</p>
<p>* You will have to on your camera during the test.</p>
<p>* During test you have to focus on the screen if your focus will be distracted then will be disqualified from the test. </p>

app/views/test_questions/_what_we_get.html.erb
<h4 style="color:blue">What we get</h4><hr>
<p>* You will have to complete the test in the given time.</p>
<p>* If you will complete the test in given time then and achieve marks with equal to passing marks then you will be awarded a certificate.</p>
<p>* You can start the test anytime within 24 hours.</p>

app/views/test_questions/edit.html.erb
<div class="container">
<h1 style="text-align:center;color:white;background-color:red">Edit Test </h1>
  <div class="card m-2 " style="width: 80rem;">
    <div class="card-body ">
    
      <%= form_with model: @test_question do |f| %>
        <div class="container-sm">

          <div class="row mb-3 mt-2">
            <strong><%= f.label :enter_description %></strong>
            <%= f.text_field :description, placeholder: "Enter description", autofocus: true, class: "form-control" %>
          </div>

         

            <div class="column mb-3 mt-2">
              <strong><%= f.label :select_language_of_question %></strong>
              <%= f.select :language_id, Language.pluck(:name, :id), {}, {data: {controller: 'slim'}}  %>
              <%# <!-- Button trigger modal -->
              <%= link_to 'Add New Language', create_ajax_languages_path , class: "btn btn-warning", data: { bs_toggle: 'modal',
                bs_target: '#newLanguageModal' } %>
              

              <!-- Modal -->
              <%# <div class="modal fade" id="newLanguageModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Language</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <%= form_with model: @language, local: false do |f1| %>
                 
                        <%# <div class="row mb-3 mt-2">
                          <strong><%= f1.label :enter_language %></strong>
                          <%# <%= f1.text_field :name, placeholder: "Enter new language", autofocus: true, class: "form-control" %>
                        <%# </div>

                        <%= f1.button "Submit", class:"btn btn-success mt-3" %>
                      <%# <%end%>
                    <%# </div>
                    
                  </div>
                </div>
              </div> %> 
              
            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :select_topic_of_question %></strong>
              <%= f.select :topic_id, Topic.pluck(:name, :id)  %>

            </div>

             <div class="column mb-3 mt-2">
              <strong><%= f.label :select_difficulty_level %></strong>
              <%= f.select :difficulty, TestQuestion.difficulties.keys.to_a %>

            </div>

           <div class="column mb-3 mt-2">
              <strong><%= f.label :select_question_type %></strong>
              <%= f.select :question_type, TestQuestion.question_types.keys.to_a %>

            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :total_number_of_question %></strong>
              <%= f.number_field :no_of_question %>
            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :passing_marks %></strong>
              <%= f.number_field :passing_marks %>
            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :full_marks %></strong>
              <%= f.number_field :full_marks %>
            </div>

            <div class="row mb-3 mt-2">
              <strong><%= f.label :coverpage_of_test %></strong>
              <%= f.file_field :image %>
            </div>

            <h3 style="color:blue;text-align:center">Add Questions and Options :- <%= @test_question.no_of_question %></h3><hr><br>

          <%= f.submit "submit", class:"btn btn-success mt-3" %>
        </div>

      <%end%>
    </div>
  </div>

</div>

app/views/test_questions/index.html.erb
<h1 style="text-align:center">All The Test with their Details</h1><hr/>
<div class="container">

  <% @test_questions.each do |question| %>
    <div class="card mb-3" style="max-width: 1200px;">
        <div class="row g-0">
          <div class="col-md-4">
            <%= image_tag question.image, :size=>"400x410" if question.image.attached? %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><b>Description :-  </b><%= question.description %></h5><br>
             <div class="container d-flex me-2">
             <div class="container">
              <strong><h5 class="card-title text-align:center">Test Details</h5></strong>
              </div>
              <div class="container">
                <% if current_user.role.eql? "admin" %>
                  <span class="badge text-bg-success"><h6>Question Uploaded :- <%= question.question_bodies.count%>/<%= question.no_of_question %></h6></span>
                <%end%>
              </div>
              </div>
              <table class="table mt-2">
                <thead>
                  <tr>
                    <th scope="col">S.No</th>
                    <th scope="col">Contents</th>
                    <th scope="col">Detail</th>
                    
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Language</td>
                    <td><%= question.language&.name || "Not Any Language Specified" %></td>
                   
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Topic</td>
                    <td><%= question.topic&.name || "Not Any Topic Specified"%></td>
                    
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>Difficulty Level</td>
                    <td><%= question.difficulty %></</td>
                    
                  </tr>
                  <tr>
                    <th scope="row">4</th>
                    <td>Type Of Question</td>
                    <td><%= question.question_type %></</td>
                    
                  </tr>
                 
                 
                </tbody>
              </table>
              <%= link_to 'Take Me to Test', test_question_path(question), class: "btn btn-primary" %>
              <% if current_user.role.eql? "admin" %>
                
                <%= link_to 'Edit Test Detail', edit_test_question_path(question), class: "btn btn-warning" %>
                <%= link_to "Delete Test", test_question_path(question), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } ,class: "btn btn-danger "%>
                <%= link_to "Add Question", new_test_question_question_body_path(question), class: "btn btn-info" %>
                
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <%end%>
</div>

app/views/test_questions/new.html.erb
<div class="container">
<h1 style="text-align:center;color:white;background-color:red">New Test </h1>
  <div class="card m-2 " style="width: 80rem;">
    <div class="card-body ">
    
      <%= form_with model: @test_question, data: {controller: 'nested-form',nested_form_wrapper_selector_value: '.nested-form-wrapper'} do |f| %>
        <div class="container-sm">

          <div class="row mb-3 mt-2">
            <strong><%= f.label :enter_description %></strong>
            <%= f.text_field :description, placeholder: "Enter description", autofocus: true, class: "form-control" %>
          </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :select_language_of_question %></strong>
              <%= f.select :language_id, Language.pluck(:name, :id), {}, {data: {controller: 'slim'}}  %>
              <%# <!-- Button trigger modal -->
              <%= link_to 'Add New Language', create_ajax_languages_path , class: "btn btn-warning", data: { bs_toggle: 'modal',
                bs_target: '#newLanguageModal' } %>
              

              <!-- Modal -->
              <%# <div class="modal fade" id="newLanguageModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Language</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <%= form_with model: @language, local: false do |f1| %>
                 
                        <%# <div class="row mb-3 mt-2">
                          <strong><%= f1.label :enter_language %></strong>
                          <%# <%= f1.text_field :name, placeholder: "Enter new language", autofocus: true, class: "form-control" %>
                        <%# </div>

                        <%= f1.button "Submit", class:"btn btn-success mt-3" %>
                      <%# <%end%>
                    <%# </div>
                    
                  </div>
                </div>
              </div> %> 
              
            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :select_topic_of_question %></strong>
              <%= f.select :topic_id, Topic.pluck(:name, :id)  %>

            </div>

             <div class="column mb-3 mt-2">
              <strong><%= f.label :select_difficulty_level %></strong>
              <%= f.select :difficulty, TestQuestion.difficulties.keys.to_a %>

            </div>

           <div class="column mb-3 mt-2">
              <strong><%= f.label :select_question_type %></strong>
              <%= f.select :question_type, TestQuestion.question_types.keys.to_a %>

            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :total_number_of_question %></strong>
              <%= f.number_field :no_of_question %>
            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :passing_marks %></strong>
              <%= f.number_field :passing_marks %>
            </div>

            <div class="column mb-3 mt-2">
              <strong><%= f.label :full_marks %></strong>
              <%= f.number_field :full_marks %>
            </div>

            <div class="row mb-3 mt-2">
              <strong><%= f.label :coverpage_of_test %></strong>
              <%= f.file_field :image %>
            </div>

            <%# <div class="container">
              <h2 style="color:blue;text-align:center">All Questions</h2><hr>
              <%= link_to_add_nested(f, :question_bodies, '#question_bodies') do %>
                <%# <span><span>Add Question</span></span>
              <%end%>
              <%# <div id="question_bodies">
                <%= f.fields_for :question_bodies do |question_body| %>
                  <%# <%= render 'question_body_fields', f: question_body %>
                <%# <% end %>
                
              <%# </div> %> 

              <%# <template data-nested-form-target="template">
                <%= form_with model: @question_body, QuestionBody.new, child_index: 'NEW_RECORD' do |question_body| %>
                  <%# <%= render "question_body_fields", f: question_body %>
                <%# <% end %>
              <%# </template>

              <%= f.fields_for :question_bodies do |question_body| %>
                <%# <%= render "question_body_fields", f: question_body %>
              <%# <%end%>

              <%# <div data-nested-form-target="target"></div>
                <button type="button" data-action="nested-form#add">Add Question</button>
              </div> %> 
            
            </div>
          
          <%= f.submit "submit", class:"btn btn-success mt-3" %>
        </div>

      <%end%>
    </div>
  </div>

</div>

app/views/test_questions/show.html.erb
<h1 style="text-align:center;color:green"> Test with their Details</h1><hr/>
<div class="card mb-3 ms-5" style="max-width: 1700px;">
  <div class="row g-0">
    <div class="col-md-4">
      <%= image_tag @test_question.image, :size=>"500x540" if @test_question.image.attached? %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title" style="color:green;"><b>Description :-  </b><%= @test_question.description %></h5><br>         
        <strong><h5 class="card-title text-align:center">Test Details</h5></strong>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">S.No</th>
              <th scope="col">Contents</th>
              <th scope="col">Detail</th>                  
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td>Language</td>
              <td><%= @test_question.language&.name || "Not Any Language Specified" %></td>                  
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>Topic</td>
              <td><%= @test_question.topic&.name || "Not Any Topic Specified"%></td>                  
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>Difficulty Level</td>
              <td><%= @test_question.difficulty %></</td>                   
            </tr>
            <tr>
              <th scope="row">4</th>
              <td>Type Of Question</td>
              <td><%= @test_question.question_type %></</td>                  
            </tr>
            <tr>
              <th scope="row">5</th>
              <td>No of Question</td>
              <td><%= @test_question.no_of_question %></</td>                   
            </tr>
              <tr>
              <th scope="row">6</th>
              <td>Full Marks</td>
              <td><%= @test_question.full_marks %></</td>                   
            </tr>
              <tr>
              <th scope="row">7</th>
              <td>Passing Marks</td>
              <td><%= @test_question.passing_marks %></</td>                   
            </tr>                
          </tbody>
        </table>
       <h5 style="color:blue;">** Please scroll down to see the test link of <%= @test_question.language&.name%>. **</h5>
       
       <%= link_to "Add Question", new_test_question_question_body_path(@test_question), class: "btn btn-warning", data: { bs_toggle: 'modal',
                bs_target: '#newQuestionModal', remote: true }   %>

        <div class="modal fade" id="newQuestionModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Question</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= form_with model: [ @test_question, @test_question.question_bodies.create ], local: false do |f1| %>
          
                <div class="row mb-3 mt-2"> 
                  <strong><%= f1.label :Enter_Question %></strong>
                  <%= f1.text_field :text, placeholder: "Enter new language", autofocus: true, class: "form-control" %>
                </div>

                

                <%= f1.button "Submit", class:"btn btn-success mt-3" %> 
              <%end%>
            </div> 
            
          </div>
        </div>
      </div> 

      </div>
    </div>
  </div>
</div>
<div class="container">
  <h3 style="text-align:center;color:red ; ">*** Read More informations. </h3>
</div>
<div class="card mb-3 ms-5" style="max-width: 1700px;">
  <div class="container">
    <div class="row g-0">
      <div class="col-md-4 mt-5">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
          <label class="form-check-label" for="flexRadioDefault1"> 
            <h6>Rules</h6><br>
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
          <label class="form-check-label" for="flexRadioDefault1"> 
            <h6>What we get</h6><br>
          </label> 
        </div>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <%= render "test_questions/rules"%>
          <%= render "test_questions/what_we_get"%>
        </div>
      </div>
      
    </div>
  </div>
</div>

<div class="container">
  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
    <label class="form-check-label" for="defaultCheck1">
      <p>I have read all the rules and regulation of this test and wants to give the test so that I can enhance my knowledge.</p>
    </label>
  </div>
  <h2 ><%= link_to "Start Test", start_test_path , class: "btn btn-outline-success btn-lg d-grid gap-2 col-6 mx-auto"%></h2>
</div>

app/views/test_questions/start_test.html.erb
<h1 style="text-align:center;color:red">Test Questions</h1><hr>
<div class="d-flex ms-2">
  
    
  
    <div class="card " style="width: 120rem; height: 25rem; overflow: auto;">
        <h5 style="text-align:center;">Total Questions</h5><hr>
        
        <div class="container ms-1">
          <% @test_question.question_bodies.in_groups_of(4, false).each do |group| %>
            <div class='row'>
              <% group.each do |product| %>
                <div class='col-md-3 '>               
                  <div class="input-group mb-3 btn btn-outline-secondary btn-lg" ><%= product.id %></div> 
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
  
  <div class="container">
  <%= form_tag submit_option_results_path do %>
    <% @all_question.each do |question| %>
  <%= hidden_field_tag :question_body_id, question.id %>
      <div class="card" style="width: 60rem;">
        <h2 class="mt-3 ms-3"><%=question.id  %>.
        <%=question.text %></h2>
      


        <% question.options.in_groups_of(4, false).each do |g| %>
          <% g.each do |p| %>
            <div class="row">
              <div class='col-md-12 '>
                <%# <h4 class="mt-3 ms-4"><%=  radio_button 'option', 'ans', p.text %> <%#=p.text</h4>  %>
                  <label>
                   <h4 class="mt-3 ms-4">
                   

                    <%= radio_button_tag :option_id, p.id, checked: true %>
                    <%= p.text%></h4> 
                  </label>

              <%# <% end %> 
              </div>
            </div>
          <% end %>
          
        <%end%>
        <%= submit_tag "Submit", class: "btn btn-success" %>
        <%# <%= link_to "submit Answer", submit_option_results_path, class: "btn btn-success"%> 
        
      </div>
      
      <%= link_to "Add Option for #{question.id}", new_question_body_option_path(question) , class: "btn btn-warning" %>
      <%# <%= link_to "Save Answer",submit_option_results_path(question), class: "btn btn-success"%> 
      
    <% end %>
    
  <%# <%end%> 
  <%end %>
  
  
  </div>
  
  <div class="container">
    <div class="card me-3" style="width: 25rem;height: 10rem">
        <h5 style="text-align:center;">My Profile</h5><hr>
        <h6 style="text-align:center">Email :- <%= current_user.email%></h6>
        <h6 style="text-align:center">Name :- <%= current_user.name%></h6>
        <%= link_to "Finish Test",root_path , data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger"%>
        
    </div>
    <div class="card me-3 mt-3" style="width: 25rem;">
        <h5 style="text-align:center;">Guidelines For this Test</h5><hr>
        <p class="ms-2">* Always allow your camera during test duration.</p>
        <p class="ms-2">* There is no negative marking system.</p>
        <p class="ms-2">* Each Question will carry equal marks.</p>
        <p class="ms-2">* Try to attempt the all questions in alloted time.</p>
        <p class="ms-2">* First read all questions then click on right option.</p>
        <p class="ms-2">* You can navigate from one question to another question.</p>
        <p class="ms-2">* After selecting option you must click submit option.</p>
        <p class="ms-2">* You have to use submit one time for particular question.</p>
        <p class="ms-2">* You are not allowed to edit option after clicked on submit button.</p>
    </div>
  </div>
</div>

   <div class=" container" style="text-align:center;">
        <h3> <%= will_paginate @all_question, :page_links => false, previous_label: "Previous Question ", next_label: " Next Question" %></h3>
  </div>

</div>


 