config/routes.rb
Rails.application.routes.draw do
  get 'user', to: 'user#index'
  resources :admin, only: [:index, :show]
  devise_for :users 
 

  root "home#index"

  resources :questions do 
    resources :options
  end

  resources :test_questions do
    resources :question_bodies
  end
  get '/test_questions/:id/start_test', to: 'test_questions#start_test', as: 'start_test'



  # resources :languages do
  #   post 'create_ajax', on: :collection
  # end

  resources :question_bodies do
    resources :options 
  end

  resources :results do
    post 'submit_option', on: :collection
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :questions
  has_many :test_questions
  has_many :topics, through: :test_questions
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :optionable, polymorphic: true
  validates :text, presence: true
  has_many :results
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :options, as: :optionable

  belongs_to :language, dependent: :destroy
  belongs_to :topic, dependent: :destroy
  
  enum difficulty: [:easy, :medium, :hard]
  enum question_type: [:Single_choice_question , :multi_choice_question]

end

app/models/question_body.rb
class QuestionBody < ApplicationRecord
  belongs_to :test_question
  has_many :options, as: :optionable
  has_many :results
  # self.per_page = 1
  validates :text, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :option
  belongs_to :question_body
end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  has_one_attached :image
  belongs_to :language, dependent: :destroy
  belongs_to :topic, dependent: :destroy
  has_many :question_bodies
  # accepts_nested_attributes_for :question_bodies, allow_destroy: true, reject_if: :all_blank

  validates :description, presence: true

  enum difficulty: [:easy, :medium, :hard]
  enum question_type: [:Single_choice_question , :multi_choice_question]

  
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :test_questions
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :results


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attribute :name, :string
  
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users = User.all
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
  end

  def index
    @questions = Question.all
    @q=Question.find(params[:question_id])
    @answers=@q.answers
  end

  def create
    question = Question.find(params[:question_id])
    @answer = question.answers.create(answer_params)
    if @answer.save
      redirect_to questions_path
    else
      render 'new'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:ans,:correct)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    if user_signed_in?
      if current_user.role.eql? "admin"
        redirect_to admin_index_path
      else
        redirect_to user_path
      end
    end
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def new
    @optionable = find_optionable
  end

  def index
    @questions = Question.all
    if params[:question_id]
      @q=Question.find(params[:question_id])
      @options=@q.options
    end
  end

  def create
    @optionable = find_optionable
    @option = @optionable.options.create(answer_params)
    # debugger
    if @option.save
      redirect_to test_questions_path
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:option).permit(:text,:correct)
  end

  def find_optionable
    if params[:question_body_id]
      QuestionBody.find(params[:question_body_id])
    elsif params[:question_id]
      Question.find(params[:question_id])
    end
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def submit_option
    # @test_question = TestQuestion.find(params[:id])
    @question_body = QuestionBody.find(params[:question_body_id])
    if params[:option_id]
      @option = Option.find(params[:option_id])
      @result = Result.create(question_body: @question_body, option: @option, user: current_user)
      # debugger
      if @result.save
        
        redirect_back(fallback_location: root_path)
      else
        
      end
    end
    @result = Result.create(question_body_id: @question_body)
  
    if @result.save
      
      redirect_back(fallback_location: root_path)
    else
      
    end
  end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController

  def index
    @topic = Topic.all
    
   
  end

  def new
    @topic = Topic.new
    
  end

  def create 
      @topic = Topic.create(question_params)
    
    if @topic.save 
         
        flash[:success] = "You have successfully created question"
        redirect_to new_question_path
    else
        render 'new'
    end
  end 

  private

  def question_params
    params.require(:topic).permit(:name)
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/index.html.erb
<h5 style="text-align:center;">admin dashboard</h5>
<br>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Last signed in</th>
    <th>Sign In Attempt</th>
    <th>Role</th>
    <th>Action</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.last_sign_in_at %></td>
      <td><%= user.sign_in_count %></td>
      <td><%= user.role %></td>
      <td><%=  %></td>
    </tr>
  <% end %>
</table>

<style>

app/views/layouts/_footer.html.erb
<div class="card text-center" style="background-color: #3f3860;">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item ">
        <a class="nav-link active text-black" aria-current="true" >Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white">Disabled</a>
      </li>
    </ul>
  </div>
  <div class="card-body text-white">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg  " style="background-color: #3f3860;">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active text-white" %>
        </li>

        

        <% if user_signed_in? %> 


          <% if current_user.role.eql? "user" %> 

            <li class="nav-item dropdown">
              <a class="nav-link text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                
                <span> <%= current_user.role.upcase  %> </span>
              </a>
              <ul class="dropdown-menu">
                <li><%=link_to "Update Profile", edit_user_registration_path, class: "nav-link active text-black" %></li>
              </ul>
            </li>

            

            <li class="nav-item">
              <a class="nav-link active text-white" href="#">Start Test</a>
            </li>

            <li class="nav-item">
              <a class="nav-link active text-white" href="#">Past Test</a>
            </li>

          <% elsif current_user.role.eql? "admin" %> 

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                
                <span> <%= current_user.role.upcase  %> </span>
              </a>
              <ul class="dropdown-menu">
                <li><%=link_to "Update Profile", edit_user_registration_path, class: "nav-link active text-black" %></li>
                <li><%=link_to "Create Test", new_test_question_path, class: "nav-link active text-black" %></li>
                <li><%= link_to "Create Practice Question", new_question_path, class: "nav-link active text-black" %></li>
              </ul>
            </li>
            
            <li class="nav-item">
              <a class="nav-link active text-white" href="#">View Users</a>
            </li>

            

          <%end%>

        <%else%>

          <li class="nav-item">
            <a class="nav-link active text-white" href="#">Start Test</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active text-white" href="#">Contact us</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active text-white" href="#">About us</a>
          </li>

        <%end%>

         <li class="nav-item">
          <%= link_to "All Tests", test_questions_path, class:"nav-link active text-white" %>
        </li>

        <li class="nav-item">

          <a class="nav-link active text-white" <%= link_to "Practice Questions", questions_path %></a>
        </li>

      </ul>
      
      <% if user_signed_in? %>      
        <a><%= link_to "Log Out" , destroy_user_session_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger me-2"  %> </a>
        
      <%else%>    
        <%= link_to "Sign up",  new_user_registration_path(@user), class: "btn btn-success me-2" %>
        <%= link_to "Log in",  new_user_session_path(@user), class: "btn btn-success me-2" %>
      <%end%>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamEagle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#jquery CDN for using Cocoon gem for nested form .%>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
    <%= javascript_importmap_tags %>
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"/>
  </head>

  <body>

   

  <%= render 'layouts/navigation'%>

  <main>
    
    <%# <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <p class="notice"><%= notice %></p>
      <%# <p class="alert"><%= alert %></p>
      <%# <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div> %> 

  
    
      <%= yield %>
    
    
  </main>
  </body>
  <%= render 'layouts/footer'%>
</html>